### ISSUE TITLE
从实现一个对话框解释DOM事件流

### ISSUE THREAD

**Issue by JaydenV8** [JaydenV8/blog#3]
# 前提
## 需求
话不多说，今天我们的产品给我们提了一个需求(模拟)：
- 实现了一个对话框。  
- 点击对话框外，隐藏对话框
- 但是不能加一层 `Mask` 

## 切图
正当我们飞快地把样式做出来：
```css
.modal {
    width: 90%;
    max-width: 500px;
    height: auto;
    min-height: 200px;
    background-color: #fff;
    box-shadow: 0 3px 10px rgba(0, 0, 0, 0.2);
    margin: auto;
    border-radius: 5px;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    display: flex;
}
```
```html
<div class="modal">
  <div style="margin: auto">点击弹窗外会消失</div>
</div>
```

效果图：

<img width="437" alt="Screen Shot 2021-05-28 at 22 06 38" src="https://user-images.githubusercontent.com/33676809/119996163-fbaec500-c000-11eb-9b76-3c019db68cd3.png">

# 正文
那么我们现在的问题来了，我们将如何实现这个效果呢

首先，我们需要从事件传递机制开始说起了。
在很多文章中，都会说到 `先捕获再冒泡`。
```
事件流描述的就是从页面中接收事件的顺序。
而 IE 和 Netscape 提出了完全相反的事件流概念。IE 事件流是事件冒泡，而 Netscape 的事件流就是事件捕获。
```

事件捕获和事件冒泡的流程就是：
- 首先进行事件捕获：   
假如我们触发一个 Button 的 [`click`](https://developer.mozilla.org/zh-TW/docs/Web/API/HTMLElement/click) 事件，会从 `window` -> `document` -> `body` -> `div` -> `button`  
从最顶层到元素一直深入到我们点击到 Button.
- 然后进行事件冒泡：  
`button` -> `div` -> `body` -> `document` -> `window`
从 Button 一直向上传递到最顶层到元素

接着，我们需要在 Javascript 中监听事件捕获和事件冒泡：
```html
<div class="level-1">
  <div class="level-2">
    <div class="level-3"></div>
  </div>
</div>
<script>
const level1 = document.querySelector('.level-1')
const level2 = document.querySelector('.level-2')
const level3 = document.querySelector('.level-3')
</script>
```
- 事件捕获
```javascript
level1.addEventListener('click', () => console.log('level-1'), true)
level2.addEventListener('click', () => console.log('level-2'), true)
level3.addEventListener('click', () => console.log('level-3'), true)

// 点击 `level-3`
// "level-1"
// "level-2"
// "level-3"
```
- 事件冒泡
```javascript
level1.addEventListener('click', () => console.log('level-1'), false)
level2.addEventListener('click', () => console.log('level-2'), false)
level3.addEventListener('click', () => console.log('level-3'), false)

// 点击 `level-3`
// "level-3"
// "level-2"
// "level-1"
```

可以看到，我们只需要在 `addEventListener` 的第三个参数里面设置 `true` 就可以监听事件捕获，默认或者设置 `false` 则为监听事件冒泡。 

### 最终实现
我们需要监听事件捕获，如果点击事件不在弹窗内则终止事件捕获，并将弹窗隐藏。
```javascript
window.addEventListener('click', event => {
  let el = event.target
  while (el && el.tagName !== 'BODY' && el !== modal) {
    el = el.parentElement
  }
  if (el !== modal) {
    event.stopPropagation() // 终止事件捕获
    // 隐藏弹窗
  }
}, true)
```

[Online Coding](https://stackblitz.com/edit/ins-modal-demo?file=index.html)
